// Field of Expertise and Department
export const FIELD_OF_EXPERTISE_OPTIONS = [
  { value: "acc_finance", label: "Accounting/ Finance" },
  { value: "architecture", label: "Architecture/ Interior Designing" },
  {
    value: "banking_insurance",
    label: "Banking/ Insurance/ Financial Services",
  },
  { value: "creative_design", label: "Creative/ Designing / Graphics" },
  {
    value: "construction_engg",
    label: "Construction/ Engineering / Architecture",
  },
  { value: "fashion_textile", label: "Fashion/ Textile Designing" },
  { value: "hospitality", label: "Hospitality" },
  { value: "it_telecom", label: "IT & Telecommunication" },
];

// Education Levels
export const EDUCATION_LEVEL_OPTIONS = [
  { value: "phd", label: "Doctorate (Ph. D)" },
  { value: "masters", label: "Graduate (Masters)" },
  { value: "professional_cert", label: "Professional Certificate" },
  { value: "bachelor", label: "Under Graduate (Bachelor)" },
  { value: "diploma", label: "Under Graduate (Bachelor)Diploma Certificate" },
  { value: "high_school", label: "Higher Secondary (+2/ A Levels/ IB)" },
  { value: "school", label: "School (SLC/ SEE)" },
  { value: "others", label: "Others" },
];

export const GENDER_OPTIONS = [
  { value: "M", label: "Male" },
  { value: "F", label: "Female" },
  { value: "X", label: "Others" },
];

// Skills
export const SKILL_OPTIONS = [
  { value: "accounting", label: "Accounting" },
  { value: "financial_analysis", label: "Financial Analysis" },
  { value: "budgeting", label: "Budgeting" },
  { value: "digital_marketing", label: "Digital Marketing" },
  { value: "social_media_marketing", label: "Social Media Marketing" },
  { value: "content_writing", label: "Content Writing" },
  { value: "javascript", label: "JavaScript" },
  { value: "python", label: "Python" },
  { value: "react", label: "React" },
  { value: "nodejs", label: "Node.js" },
  { value: "html_css", label: "HTML/CSS" },
  { value: "sql", label: "SQL" },
  { value: "mongodb", label: "MongoDB" },
  { value: "git", label: "Git" },
  { value: "docker", label: "Docker" },
  { value: "aws", label: "AWS" },
  { value: "project_management", label: "Project Management" },
  { value: "team_leadership", label: "Team Leadership" },
  { value: "communication", label: "Communication" },
  { value: "problem_solving", label: "Problem Solving" },
  { value: "critical_thinking", label: "Critical Thinking" },
  { value: "time_management", label: "Time Management" },
  { value: "adaptability", label: "Adaptability" },
  { value: "creativity", label: "Creativity" },
  { value: "analytical_thinking", label: "Analytical Thinking" },
  { value: "customer_service", label: "Customer Service" },
  { value: "sales", label: "Sales" },
  { value: "marketing", label: "Marketing" },
  { value: "graphic_design", label: "Graphic Design" },
  { value: "ui_ux_design", label: "UI/UX Design" },
  { value: "photoshop", label: "Photoshop" },
  { value: "illustrator", label: "Illustrator" },
  { value: "figma", label: "Figma" },
  { value: "excel", label: "Microsoft Excel" },
  { value: "powerpoint", label: "Microsoft PowerPoint" },
  { value: "word", label: "Microsoft Word" },
  { value: "data_analysis", label: "Data Analysis" },
  { value: "machine_learning", label: "Machine Learning" },
  { value: "artificial_intelligence", label: "Artificial Intelligence" },
  { value: "cybersecurity", label: "Cybersecurity" },
  { value: "network_administration", label: "Network Administration" },
  { value: "database_management", label: "Database Management" },
  { value: "quality_assurance", label: "Quality Assurance" },
  { value: "testing", label: "Testing" },
  { value: "agile_methodology", label: "Agile Methodology" },
  { value: "scrum", label: "Scrum" },
  { value: "devops", label: "DevOps" },
  { value: "cloud_computing", label: "Cloud Computing" },
  { value: "mobile_development", label: "Mobile Development" },
  { value: "ios_development", label: "iOS Development" },
  { value: "android_development", label: "Android Development" },
  { value: "flutter", label: "Flutter" },
  { value: "react_native", label: "React Native" },
];

// Department uses Field of Expertise options
export const DEPARTMENT_OPTIONS = FIELD_OF_EXPERTISE_OPTIONS;

// Districts of Nepal
export const DISTRICT_OPTIONS = [
  { value: "achham", label: "Achham" },
  { value: "arghakhanchi", label: "Arghakhanchi" },
  { value: "baglung", label: "Baglung" },
  { value: "baitadi", label: "Baitadi" },
  { value: "bajhang", label: "Bajhang" },
  { value: "bajura", label: "Bajura" },
  { value: "banke", label: "Banke" },
  { value: "bara", label: "Bara" },
  { value: "bardiya", label: "Bardiya" },
  { value: "bhaktapur", label: "Bhaktapur" },
  { value: "bhojpur", label: "Bhojpur" },
  { value: "chitwan", label: "Chitwan" },
  { value: "dadeldhura", label: "Dadeldhura" },
  { value: "dailekh", label: "Dailekh" },
  { value: "dang", label: "Dang" },
  { value: "darchula", label: "Darchula" },
  { value: "dhading", label: "Dhading" },
  { value: "dhankuta", label: "Dhankuta" },
  { value: "dhanusha", label: "Dhanusha" },
  { value: "dholkha", label: "Dholkha" },
  { value: "dolpa", label: "Dolpa" },
  { value: "doti", label: "Doti" },
  { value: "eastern_rukum", label: "Eastern Rukum" },
  { value: "gorkha", label: "Gorkha" },
  { value: "gulmi", label: "Gulmi" },
  { value: "humla", label: "Humla" },
  { value: "ilam", label: "Ilam" },
  { value: "jajarkot", label: "Jajarkot" },
  { value: "jhapa", label: "Jhapa" },
  { value: "jumla", label: "Jumla" },
  { value: "kailali", label: "Kailali" },
  { value: "kalikot", label: "Kalikot" },
  { value: "kanchanpur", label: "Kanchanpur" },
  { value: "kapilvastu", label: "Kapilvastu" },
  { value: "kaski", label: "Kaski" },
  { value: "kathmandu", label: "Kathmandu" },
  { value: "kavrepalanchok", label: "Kavrepalanchok" },
  { value: "khotang", label: "Khotang" },
  { value: "lalitpur", label: "Lalitpur" },
  { value: "lamjung", label: "Lamjung" },
  { value: "mahottari", label: "Mahottari" },
  { value: "makwanpur", label: "Makwanpur" },
  { value: "manang", label: "Manang" },
  { value: "morang", label: "Morang" },
  { value: "mugu", label: "Mugu" },
  { value: "mustang", label: "Mustang" },
  { value: "myagdi", label: "Myagdi" },
  { value: "nawalparasi_east", label: "Nawalparasi (East)" },
  { value: "nawalparasi_west", label: "Nawalparasi (West)" },
  { value: "nuwakot", label: "Nuwakot" },
  { value: "okhaldhunga", label: "Okhaldhunga" },
  { value: "palpa", label: "Palpa" },
  { value: "panchthar", label: "Panchthar" },
  { value: "parbat", label: "Parbat" },
  { value: "parsa", label: "Parsa" },
  { value: "pyuthan", label: "Pyuthan" },
  { value: "ramechhap", label: "Ramechhap" },
  { value: "rasuwa", label: "Rasuwa" },
  { value: "rautahat", label: "Rautahat" },
  { value: "rolpa", label: "Rolpa" },
  { value: "rukum_east", label: "Rukum (East)" },
  { value: "rukum_west", label: "Rukum (West)" },
  { value: "rupandehi", label: "Rupandehi" },
  { value: "salyan", label: "Salyan" },
  { value: "sankhuwasabha", label: "Sankhuwasabha" },
  { value: "saptari", label: "Saptari" },
  { value: "sarlahi", label: "Sarlahi" },
  { value: "sindhuli", label: "Sindhuli" },
  { value: "sindhupalchok", label: "Sindhupalchok" },
  { value: "siraha", label: "Siraha" },
  { value: "solukhumbu", label: "Solukhumbu" },
  { value: "sunsari", label: "Sunsari" },
  { value: "surkhet", label: "Surkhet" },
  { value: "syangja", label: "Syangja" },
  { value: "tanahun", label: "Tanahun" },
  { value: "taplejung", label: "Taplejung" },
  { value: "terhathum", label: "Terhathum" },
  { value: "udayapur", label: "Udayapur" },
];

export const JOB_BY_TITLE = [
  { value: "seniordeveloper", label: "Senior Developer" },
  { value: "accountant", label: "Accountant" },
  { value: "financialanalyst", label: "Financial Analyst" },
  { value: "registerednurse", label: "Registered Nurse" },
  { value: "marketingmanager", label: "Marketing Manager" },
  { value: "hrspecialist", label: "HR Specialist" },
  { value: "graphicdesigner", label: "Graphic Designer" },
  { value: "datascientist", label: "Data Scientist" },
];

export const JOB_BY_TIME = [
  { value: "fulltime", label: "Full Time" },
  { value: "parttime", label: "Part Time" },
  { value: "contract", label: "Contract" },
  { value: "internship", label: "Internship" },
  { value: "freelance", label: "Freelance" },
];

export const JOB_BY_LOCATION = [
  { value: "on_site", label: "On-Site / In-Office" },
  { value: "remote", label: "Remote" },
  { value: "hybrid", label: "Hybrid" },
  { value: "none", label: "Not Specified" },
];

export const JOB_BY_LEVEL = [
  { value: "intern", label: "Intern" },
  { value: "junior", label: "Junior" },
  { value: "mid-level", label: "Mid Level" },
  { value: "senior", label: "Senior" },
];

export const SALARY_TYPE = [
  { value: "hourly", label: "Hourly" },
  { value: "daily", label: "Daily" },
  { value: "weekly", label: "Weekly" },
  { value: "monthly", label: "Monthly" },
  { value: "yearly", label: "Yearly" },
];

export const EXPERIENCE_CRITERIA_OPTIONS = [
  { value: "more_than", label: "More than" },
  { value: "less_than", label: "Less than" },
  { value: "more_than_or_equal_to", label: "More than or equal to" },
  { value: "less_than_or_equal_to", label: "Less than or equal to" },
  { value: "equal_to", label: "Equal to" },
];

export const EXPERIENCE_OPTIONS = [
  { value: "1year", label: "1 Year" },
  { value: "2years", label: "2 Years" },
  { value: "3years", label: "3 Years" },
  { value: "4years", label: "4 Years" },
  { value: "5+years", label: "5+ Years" },
];
